# Generated by Django 4.2.15 on 2024-08-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('1', 'Available'), ('2', 'Reserved'), ('0', 'Cancelled')], default='available', max_length=10),
        ),
    ]
