# Generated by Django 4.2.15 on 2024-08-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_status_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(1, 'Confirmed'), (0, 'Cancelled')], default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.IntegerField(choices=[(1, 'Admin'), (0, 'Customer')], default=0),
        ),
    ]
