# Generated by Django 4.2.15 on 2024-08-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_table_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(1, 'Confirmed'), (0, 'Cancelled')], default=0),
        ),
    ]
