# Generated by Django 4.2.15 on 2024-08-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(1, 'available'), (0, 'Cancelled')], default=1),
        ),
    ]
