# Generated by Django 4.2.15 on 2024-08-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('table', 'booking_date', 'booking_time', 'status'), name='unique_booking_per_table_per_time'),
        ),
    ]
