# Generated by Django 4.2.15 on 2024-08-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(1, 'Confirmed'), (0, 'Cancelled'), (2, 'Available')], default=1),
        ),
    ]
