# Generated by Django 4.2.15 on 2024-08-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(2, 'Confirmed'), (0, 'Cancelled'), (1, 'Available')], default=2),
        ),
    ]
