# Generated by Django 4.2.15 on 2024-08-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='status',
            field=models.IntegerField(choices=[(1, 'Available'), (0, 'Not Available')], default=1),
        ),
    ]
