# Generated by Django 4.2.15 on 2024-08-27 14:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
